### ISSUE TITLE
Custom prefix with bactopia-prepare causes error. 

### ISSUE THREAD

**Issue by rwilliams** [bactopia/bactopia-py#1]
I used the same syntax as the example from https://github.com/bactopia/bactopia/issues/176

Command used:

`bactopia-prepare -p input --assembly-ext .fasta -s "Streptococcus suis" --prefix s3://test/ > fofn.txt`

Error:
```
/home/ubuntu/.local/lib/python3.10/site-packages/bactopia/cli/prepare.py:127 in get_path         
│                                                                                                  
│   126 │   if prefix:                                                                             
│ ❱ 127 │   │   return fastq_path.replace(abspath, prefix).replace("///", "//")                    
│   128 │   return fastq_path    
```

**Comment by rpetit3** [comment]
You are right! Noticed that yesterday when I was updating the tutorial.

I'll get this fixed! Thank you for the reminder!

**Comment by rpetit3** [comment]
Super simple fix https://github.com/bactopia/bactopia-py/commit/3f0c46cb5a0ab0435460716994ff05cd7acf804e, forgot to convert `Path` to a string. I submitted a new release, it will take some time to get things synced (pypi, bioconda, bactopia)


Thanks again for posting the issue! Feel free to reopen if it still gives you problems.
